#!/usr/bin/env bash

TOP_DIR=$(dirname $(readlink -f "${0}"))
SCRIPT_NAME=$(basename "${0}")
NBB=${TOP_DIR}/node_modules/.bin/nbb

die() { echo >&2 "${*}"; exit 1; }

[ -e "${NBB}" ] || die "Missing ${NBB}. Maybe run 'npm install' in ${TOP_DIR}?"

exec ${NBB} -cp "${TOP_DIR}/src" -m conlink.net2dot/main "${@}"
