type: object
additionalProperties: false
required: ["links"]
properties:
  links:
    type: array
    items:
      type: object
      oneOf: [{required: ["container"]},
              {required: ["service"]}]

      if:   {properties: {type: {const: "veth"}}}
      then:
        allOf:
          - {required: ["bridge"]}
          - {not: {required: ["vlanid"]}}
      else:
        not: {required: ["bridge"]}
        if:   {properties: {type: {const: "vlan"}}}
        then: {required: ["vlanid"]}
        else: {not: {required: ["vlanid"]}}

      additionalProperties: false
      properties:
        type:
          type: string
          default: "veth"
          enum: [veth, dummy, vlan, ipvlan, ipvtap, macvlan, macvtap]
        service:   {type: string}
        container: {type: string}
        bridge:    {type: string}
        dev:       {type: string, default: "eth0"}
        ip:        {type: string, pattern: "^([0-9]{1,3}[.]){3}[0-9]+/[0-9]*$"}
        mac:       {type: string, pattern: "^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$"}
        mtu:       {type: number}
        route:     {type: string}
        vlanid:    {type: number}
        nat:       {type: string, pattern: "^([0-9]{1,3}[.]){3}[0-9]+/[0-9]*$"}

  commands:
    type: array
    items:
      type: object
      required: ["command"]
      oneOf: [{required: ["container"]},
              {required: ["service"]}]
      properties:
        service:   {type: string}
        container: {type: string}
        command:   {type: string}
