$defs:
  cidr: {type: string, pattern: "^([0-9]{1,3}[.]){3}[0-9]+/[0-9]*$"}
  ip:   {type: string, pattern: "^([0-9]{1,3}[.]){3}[0-9]+$"}
  mac:  {type: string, pattern: "^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$"}
  intf: {type: string, pattern: "^.{1,15}$"}
  fwd:  {type: string, pattern: "^[0-9]{1,5}:[0-9]{1,5}/(tcp|udp)$"}

type: object
additionalProperties: false
required: ["links"]
properties:
  links:
    type: array
    items:
      type: object
      oneOf: [{required: ["container"]},
              {required: ["service"]}]

      if:   {properties: {type: {const: "veth"}}}
      then:
        allOf:
          - {required: ["bridge"]}
          - {not: {required: ["mode", "vlanid"]}}
      else:
        not: {required: ["bridge"]}
        if:   {properties: {type: {const: "vlan"}}}
        then: {required: ["vlanid"]}
        else: {not: {required: ["mode", "vlanid"]}}

      additionalProperties: false
      properties:
        type:
          type: string
          default: "veth"
          enum: [veth, dummy, vlan, ipvlan, ipvtap, macvlan, macvtap]
        service:   {type: string}
        container: {type: string}
        bridge:    {type: string}
        outer-dev: {type: string, pattern: "^.{1,15}$"}
        dev:       {type: string, pattern: "^.{1,15}$", default: "eth0"}
        ip:        { "$ref": "#/$defs/cidr" }
        mac:       { "$ref": "#/$defs/mac" }
        mtu:       {type: number}
        nat:       { "$ref": "#/$defs/ip" }
        mode:      {type: string}
        vlanid:    {type: number}
        route:
          oneOf: [{type: string},
                  {type: array, items: {type: string}}]
        forward:
          oneOf: [{ "$ref": "#/$defs/fwd" },
                  {type: array, items: { "$ref": "#/$defs/fwd" }}]
        netem:
          oneOf: [{type: string},
                  {type: array, items: {type: string}}]
        ethtool:
          oneOf: [{type: string},
                  {type: array, items: {type: string}}]

  bridges:
    type: array
    items:
      type: object
      properties:
        mode: {type: string, enum: [auto, ovs, linux, patch]}

  tunnels:
    type: array
    items:
      type: object
      required: ["type", "bridge", "remote", "vni"]
      properties:
        type:      {type: string, enum: [geneve, vxlan]}
        bridge:    {type: string}
        remote:    { "$ref": "#/$defs/ip" }
        vni:       {type: number}
        netem:
          oneOf: [{type: string},
                  {type: array, items: {type: string}}]

  commands:
    type: array
    items:
      type: object
      required: ["command"]
      oneOf: [{required: ["container"]},
              {required: ["service"]}]
      properties:
        service:   {type: string}
        container: {type: string}
        command:   {type: string}
