# A docker-compose file with an external network configuration file
# and two docker containers that are connected via a switch. In
# addition an "internet" host is setup in the network container that
# is also connected to the switch and is listening on 8.8.8.8.

version: "2.4"

services:
  network:
    build: {context: .}
    image: conlink
    pid: host
    network_mode: none
    cap_add: [SYS_ADMIN, SYS_NICE, NET_ADMIN]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - ./:/test
    command: /sbin/conlink.py /test/test2-compose.yaml --network-file /test/test2-network.yaml

  node1:
    image: alpine
    cap_add: [NET_ADMIN]
    network_mode: none
    command: sleep 864000

  node2:
    image: alpine
    cap_add: [NET_ADMIN]
    network_mode: none
    command: sleep 864000
