version: "2.4"

x-network:
  mininet-cfg:
    switches:
      - name: s0
    hosts:
      - name: r0
        opts: {ip: "10.0.0.100/24"}
    links:
      - left:  s0
        right: r0
        opts:  {intfName1: 's0-r0-eth0',
                intfName2: "eth0", params2: {ip: "10.0.0.100/24"}}
    commands:
      - node: r0
        command: "sysctl net.ipv4.ip_forward=1"

services:
  network:
    build: {context: ../..}
    image: conlink
    pid: host
    network_mode: none
    cap_add: [SYS_ADMIN, NET_ADMIN, SYS_NICE, NET_BROADCAST, IPC_LOCK]
    security_opt: [ 'apparmor:unconfined' ] # needed on Ubuntu 18.04
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - ../../:/test
    working_dir: /test
    command: /sbin/conlink --compose-file ${COMPOSE_FILE:-examples/test7-multiple/base-compose.yaml}

