version: "2.4"

x-network:
  mininet-cfg:
    switches:
      - name: s1
    links:
      - left:  s1
        right: r0
        opts:  {intfName1: 's1-r0-eth1',
                intfName2: "eth1", params2: {ip: "10.1.0.100/24"}}

services:
  network:
    command: /sbin/conlink --compose-file ${COMPOSE_FILE:-examples/test7-multiple/node1-compose.yaml}

  node1:
    image: alpine
    cap_add: [NET_ADMIN]
    network_mode: none
    command: sleep 864000
    x-network:
      commands:
        - container: node1_1
          command: ip route add default via 10.1.0.100
      links:
        - left:  {container: node1_1,   intf:       eth0,  ip: 10.1.0.1/16}
          right: {container: network_1, intf: node1-eth0}
      mininet-cfg:
        interfaces:
          - name: node1-eth0
            node: s1
