# A docker-compose file with an external network configuration file
# and docker containers that are connected via a switch. The
# "internet" container is setup that is also connected to the switch
# and is listening on 8.8.8.8 (to test routing from the nodes).

version: "2.4"

services:
  network:
    build: {context: ../}
    image: conlink
    pid: host
    network_mode: none
    cap_add: [SYS_ADMIN, NET_ADMIN, SYS_NICE, NET_BROADCAST, IPC_LOCK]
    security_opt: [ 'apparmor:unconfined' ] # needed on Ubuntu 18.04
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - ./:/test
    command: /app/build/conlink.js inner --verbose --compose-file /test/test2-compose.yaml --network-file /test/test2-network.yaml

  node:
    image: alpine
    network_mode: none
    scale: 2
    command: sleep 864000

  internet:
    image: alpine
    network_mode: none
    command: sleep 864000
