# Test Topology:
#
#       r0
#       /|\
#      / | \
#    s1 s2  s3
#    /   |   \
#   /    |    \
#  h1   h2    h3
#

version: "2.4"

services:
  r0:
    image: alpine
    network_mode: none
    command: "sleep 864000"
    x-network:
      links:
        - {bridge: s1, dev: eth-s1, ip: "192.168.1.1/24"}
        - {bridge: s2, dev: eth-s2, ip: "172.16.0.1/12"}
        - {bridge: s3, dev: eth-s3, ip: "10.0.0.1/8"}

  h1:
    image: alpine
    network_mode: none
    command: "sleep 864000"
    x-network:
      links:
        - {bridge: s1, ip: "192.168.1.100/24", route: "default via 192.168.1.1"}

  h2:
    image: alpine
    network_mode: none
    command: "sleep 864000"
    x-network:
      links:
        - {bridge: s2, ip: "172.16.0.100/12",  route: "default via 172.16.0.1"}

  h3:
    image: alpine
    network_mode: none
    command: "sleep 864000"
    x-network:
      links:
        - {bridge: s3, ip: "10.0.0.100/8",     route: "default via 10.0.0.1"}

  network:
    build: {context: ../}
    image: conlink
    pid: host
    network_mode: none
    cap_add: [SYS_ADMIN, NET_ADMIN, SYS_NICE, NET_BROADCAST, IPC_LOCK]
    security_opt: [ 'apparmor:unconfined' ] # needed on Ubuntu 18.04
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - ./:/test
    command: /app/build/conlink.js --compose-file /test/test1-compose.yaml
