name: Push (compose tests)

on:
  push: {}
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  compose-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: npm install
        run: npm install

      - name: compose build of conlink
        run: docker compose -f examples/test1-compose.yaml build

      - name: "./run-tests.sh"
        timeout-minutes: 5
        run: time ./run-tests.sh
